name: test_ali
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  modal_progress_hud_nsn: ^0.5.1
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  firebase_storage: ^12.4.3
  shared_preferences: ^2.5.2
  image_card: ^0.0.4
  camera: ^0.11.1
  firebase_core: ^3.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

