// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhsrljRh9vht2pvLvZCm1KNd7Uz44ljdQ',
    appId: '1:877168834366:web:998f501d66a89a8d0c9e6f',
    messagingSenderId: '877168834366',
    projectId: 'tourscan',
    authDomain: 'tourscan.firebaseapp.com',
    storageBucket: 'tourscan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjyDwgNqV9wkm0xr0A5BqS_K02UJXQ9cU',
    appId: '1:877168834366:android:ba07f762d24fe37b0c9e6f',
    messagingSenderId: '877168834366',
    projectId: 'tourscan',
    storageBucket: 'tourscan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEE7968vHVMOuL7KDcRwzFkWkVw_MqD5M',
    appId: '1:877168834366:ios:65e71f8b072051bd0c9e6f',
    messagingSenderId: '877168834366',
    projectId: 'tourscan',
    storageBucket: 'tourscan.firebasestorage.app',
    iosBundleId: 'com.example.testAli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEE7968vHVMOuL7KDcRwzFkWkVw_MqD5M',
    appId: '1:877168834366:ios:65e71f8b072051bd0c9e6f',
    messagingSenderId: '877168834366',
    projectId: 'tourscan',
    storageBucket: 'tourscan.firebasestorage.app',
    iosBundleId: 'com.example.testAli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhsrljRh9vht2pvLvZCm1KNd7Uz44ljdQ',
    appId: '1:877168834366:web:71198184755b8e1f0c9e6f',
    messagingSenderId: '877168834366',
    projectId: 'tourscan',
    authDomain: 'tourscan.firebaseapp.com',
    storageBucket: 'tourscan.firebasestorage.app',
  );
}
